### ISSUE TITLE
Class 'mongosoft\file\UploadBehavior' not found

### ISSUE THREAD

**Issue by fedornabilkin** [karpoff/yii2-crop-image-upload#16]
Здравствуйте. Оказалось, что mongosoft переименован в mohorev. В связи с этим репозитория https://github.com/mongosoft/yii2-upload-behavior больше не существует. Вместо этого есть https://github.com/mohorev/yii2-upload-behavior

Подскажите, пожалуйста, как исправить эту ошибку. Ошибка возникла после composer update :)
Пока откатил mongosoft/yii2-upload-behavior до версии 0.1.7

**Comment by karpoff** [comment]
Добрый день.
Можно переименовать и создать PullRequest)

**Comment by karpoff** [comment]
а, там даже уже был
замерджил

**Comment by temirfe** [comment]
добавил "karpoff/yii2-crop-image-upload": "*" в composer.json, до сих пор выходит это ошибка (
